DominikPieper/obsidian-ReadItLater

src/parsers/TextSnippetParser.ts
src/parsers/TwitterParser.ts
src/parsers/WebsiteParser.ts
src/parsers/YoutubeParser.ts

Replaces the variable name string in the replace call with a corresponding RegEx with a global flag so that all occurrences will be replaced.

Allow multiple uses of variables in note templates

---

src/helpers/fileutils.ts
src/parsers/WebsiteParser.ts

Hi @DominikPieper 
this PR provides a fix for #40 . It also contains refactor of getBaseUrl function to use native URL object for relative paths support.

Fix relative path in base element

---

src/main.ts
src/parsers/BilibiliParser.ts
src/settings.ts
src/views/settings-tab.ts

This PR provides support for embedding videos from Bilibili.com and adds two new template settings for it.
#39

Add support for Bilibili embed

---

src/parsers/TextSnippetParser.ts

Fix text snippet title template

---

.github/workflows/release.yml
.gitignore
package-lock.json

- fix version number by adding --tags option
- use up-to-date versions of Github Actions
- use Node.js v16 to build
- add package-lock.json to use same dependencies

Update release process

---

src/helpers/downloadImage.ts
src/helpers/fileutils.ts
src/helpers/linkHash.ts
src/helpers/replaceImages.ts
src/parsers/TextSnippetParser.ts
src/parsers/WebsiteParser.ts
src/parsers/parsehtml.ts
src/views/settings-tab.ts

- Fix #62 
- Fix saving images linked with query string
- Fix ESLint errors and warnings

Fix CORS image download and escape asset folder name

---

src/parsers/WebsiteParser.ts

This PR adds estimated reading time of article as content template variable. 
Estimated reading time is calculated as division of article's word count and average word reading speed according to [this study](https://irisreading.com/average-reading-speed-in-various-languages/).

Add estimated reading time as template variable

---

src/parsers/WebsiteParser.ts
src/views/settings-tab.ts

Exposed %author% (byline) and %siteName% and updated description in settings.

Exposed %author% and %siteName%

---

.eslintrc.js
package-lock.json
package.json
src/helpers/fileutils.ts
src/helpers/replaceImages.ts
src/parsers/BilibiliParser.ts
src/parsers/MastodonParser.ts
src/parsers/Parser.ts
src/parsers/StackExchangeParser.ts
src/parsers/TextSnippetParser.ts
src/parsers/TwitterParser.ts
src/parsers/VimeoParser.ts
src/parsers/WebsiteParser.ts
src/parsers/YoutubeParser.ts

Update of NPM depdencies and ESLint configuration.
Use up-to date dependencies and have advanced ESLint configuration to prevent different codestyles.
By doing build.
Not applicable.

chore: Update npm dependencies and eslint configuration

---

src/parsers/YoutubeParser.ts

Regex edit for reliable support of Youtube Shorts
Support new Youtube video format.
Tested with multiple Youtube Shorts posts:
- https://www.youtube.com/shorts/-7DAbEWZoGs
- https://www.youtube.com/shorts/pvEZELnbPoI
- https://www.youtube.com/shorts/qLxyxOWQDj4

feat: Youtube Shorts embed

---

README.md
package-lock.json
package.json
src/helpers/error.ts
src/helpers/index.ts
src/parsers/YoutubeParser.ts
src/settings.ts
src/views/settings-tab.ts

This PR adds option to fetch data about YouTube videos from [Data API](https://developers.google.com/youtube/v3/getting-started). Besides that, new template variables are introduced.
Limited amount of available data from HTML DOM. YouTube Data API provides more information.
Tested on multiple public videos such as:
- https://www.youtube.com/watch?v=Wg4YfEXK8R8
- https://www.youtube.com/watch?v=FsNGxsrcZas
Tested on desktop and Android smartphone with latest Obsidian releases.

feat: Fetching data from YouTube API

---

src/views/settings-tab.ts

Add new settings fields for TikTok parser.
I forgot to include this file in #94 :laughing: 

fix: Add TikTok settings to UI

---

src/parsers/YoutubeParser.ts
src/settings.ts
src/views/settings-tab.ts

This PR enables embedding of YouTube videos in privacy enhanced mode. This mode is enabled by default and can be turned off in settings.
Feature request by user.
Saving of these videos:
- https://www.youtube.com/watch?v=YaPe8DgI0y4
- https://www.youtube.com/shorts/ak_F8x4giIo

feat: Privacy enhanced mode for YouTube embeds 

---

README.md
src/parsers/TwitterParser.ts

This PR adds new template variable for TwitterParser - %tweetPublishDate%. Value of it is parsed from Twitter Publish API response.
Feature requested by user.
By saving these posts:
- https://twitter.com/freekmurze/status/1701949652654825959
- https://twitter.com/elonmusk/status/1703348962697396461

feat: Add publish date variabe for TwitterParser

---

README.md
src/parsers/YoutubeParser.ts
src/views/settings-tab.ts

- prioritize thumbnails without black borders
- load thumbnail from OpenGraph markup
Saving various Youtube videos such as:
- https://www.youtube.com/watch?v=tO9k6CJEFnw
- https://www.youtube.com/watch?v=5ycs4K1LnrA

fix: youtube thumbnails

---

README.md
src/helpers/date.ts
src/helpers/index.ts
src/helpers/replaceImages.ts
src/parsers/Parser.ts
src/parsers/WebsiteParser.ts
src/views/settings-tab.ts

Including small refactor regarding date foramtting.

feat: Add publishedTime variable to WebsiteParser

---

src/parsers/WebsiteParser.ts

Fixes missing Substack headings with DOM optimizations from markdownload extension

fix: substack heading

---

package-lock.json
package.json
src/parsers/Parser.ts
src/parsers/WebsiteParser.ts
src/views/settings-tab.ts

Update dependencies to fix eslint warnings

chore: update dependencies

---

src/parsers/WebsiteParser.ts

Fixes saving of not parseable article in WebsiteParser.

fix: Save not parseable article

---

src/helpers/fileutils.ts
src/helpers/replaceImages.ts

trying to save a website that contained a data uri image got stuck, now they get ignored
fixes https://github.com/DominikPieper/obsidian-ReadItLater/discussions/146
with the provided link

ignore data uri images

---

src/parsers/WebsiteParser.ts
src/parsers/YoutubeParser.ts
src/parsers/parsehtml.ts
tsconfig.json

Enhancing parsing of Github repository.
Reported in #132 .
Saving multiple Github Repositories:
- https://github.com/DominikPieper/obsidian-ReadItLater
- https://github.com/octokit/core.js
- https://github.com/laravel/framework

feat: Enhance Github parsing

---

src/main.ts
src/parsers/WikipediaParser.ts

Resolves multiple Wikipedia issues such as:
- https://github.com/DominikPieper/obsidian-ReadItLater/issues/174
- https://github.com/DominikPieper/obsidian-ReadItLater/issues/176

feat: wikipedia parser

---

package-lock.json
src/helpers/fileutils.ts
src/helpers/platform.ts
src/main.ts
src/settings.ts
src/views/settings-tab.ts

Each OS has different limitations on saving files. This PR adds default limits and new settings to enter your own limits.
Fixes #160 and based on #162 .

feat: Add file name and path limitations

---

src/views/settings-tab.ts

Fix for broken settings view caused by call to removed function.

hotfix: settings view

---

.eslintrc.js
README.md
src/helpers/domUtils.ts
src/helpers/numberUtils.ts
src/main.ts
src/parsers/YoutubeChannelParser.ts
src/parsers/YoutubeParser.ts
src/settings.ts
src/template/TemplateEngine.ts
src/views/settings-tab.ts

Adds new parser Youtube Channel.
User requrested feature in #120 
Creating notes from various Youtube Channel URLs:
- https://www.youtube.com/@GamersNexus
- https://www.youtube.com/c/D%C5%98EVOSTAVBYsPavlem%C5%A0imkem
- https://www.youtube.com/@weaverryan

feat: Youtube channel parser

---

src/parsers/parsehtml.ts

Enhance of Torchlight codeblocks parsing.
Parsing multiple sites using Torchlight codeblocks such as:
- https://aschmelyun.com/blog/installing-a-local-composer-package-in-your-php-project/
- https://laravel.com/docs/11.x/passwords

feat: enhance torchlight codeblocks

---

manifest.json
package.json
src/NoteService.ts
src/ReadtItLaterApi.ts
src/enums/delimiter.ts
src/enums/enum.ts
src/enums/fileExistsStrategy.ts
src/error/FileExists.ts
src/error/FileNotFound.ts
src/helpers/setting.ts
src/helpers/stringUtils.ts
src/main.ts
src/modal/FileExistsAsk.ts
src/parsers/MastodonParser.ts
src/parsers/Note.ts
src/parsers/Parser.ts
src/parsers/StackExchangeParser.ts
src/parsers/WebsiteParser.ts
src/parsers/YoutubeChannelParser.ts
src/parsers/YoutubeParser.ts
src/parsers/parsehtml.ts
src/repository/DefaultVaultRepository.ts
src/repository/VaultRepository.ts
src/settings.ts
src/views/settings-tab.ts

Compromise feature for user request #111 .
Exposed plugin API requested in #178 

feat: Add behavior for duplicate notes

---

src/parsers/WebsiteParser.ts

Provides fix for parsing HTML in other charsets than UTF-8.
Fixes #136 

fix: parsing different charsets

---

README.md
src/helpers/networkUtils.ts
src/main.ts
src/parsers/BlueskyParser.ts
src/parsers/GithubParser.ts
src/parsers/PinterestParser.ts
src/parsers/StackExchangeParser.ts
src/parsers/WebsiteParser.ts
src/parsers/WikipediaParser.ts
src/parsers/YoutubeChannelParser.ts
src/parsers/YoutubeParser.ts
src/settings.ts
src/views/settings-tab.ts

feat: Pinterest parser

---

src/parsers/WebsiteParser.ts

Fix displaying images for sites that uses markup div > figure such as https://www.anthropic.com/research/building-effective-agents

fix: div figure image

---

src/views/settings-tab.ts
styles.css

Provides new UI for plugin settings. Each content type settings is collapsible.
As plugin has more supported content types amount of scrolling was unbearable.

feat: new settings ui

---

src/parsers/PinterestParser.ts
src/settings.ts

fix: pinterest template

---

src/helpers/domUtils.ts
src/parsers/PinterestParser.ts
src/parsers/YoutubeParser.ts

Provides fix for Youtube content types:
- fix wrong json variable name
- fix retrieving channelId
- fix parsing Youtube channel JSON data

hotfix: youtube content types

---

src/parsers/WebsiteParser.ts

Provides fix for parsing WeChat site.
User reported bug in #187 

hotfix: wechat parsing
