- src/parsers/YoutubeParser.ts
Fixes an issue where all YouTube videos were returning "YouTube" for title variable.
> Select og:title from YouTube metadata

- src/parsers/Parser.ts
- src/parsers/TextSnippetParser.ts
- src/parsers/TwitterParser.ts
- src/parsers/WebsiteParser.ts
- src/parsers/YoutubeParser.ts
- src/settings.ts
- src/views/settings-tab.ts
This PR provides a `%date%` variable to be used in all templates content.
Moreover, since the `%date%` used in titles might require different format than the one in content templates, this PR also add settings to configure both independently.
> Add %date% variable for content in templates

- src/parsers/YoutubeParser.ts
This PR provides fix for #43. 
It adds user-agent header with value of Chrome on Windows 10 to force loading of desktop YouTube site. Mobile site doesn't provide <meta> element with og:title attribute and content of <title> element is injected by Javascript.
> Fix embeding YouTube videos for mobile apps

- src/helpers/fileutils.ts
This PR provides fix for #46 and #34. Currently only the first occurrence of illegal symbol is replaced in filename. I refactored normalizeFilename function to use regex with global modifier and tested it on provided URLs in issues.
> Fix replace illegal symbols in filename

- src/parsers/WebsiteParser.ts
- src/settings.ts
- src/views/settings-tab.ts
This commit changes the behavior from  downloading images in assets to downloading in `assets/{note name}/` so that when you want to delete a note or move it you know where the assets are.
It partially solves #50 as it doen't give the suggested solution but it gives a way to identify per note assets 😁
> Use a folder for assets inside the assets folder

- src/parsers/WebsiteParser.ts
Fixes #60 Unable to save non-parsable webpages.
Seems there was a typo in `WebsiteParsesr` `notParsableArticle/1`. The new note's filename was being set to `notParsableArticleNote` instead of `notParseableArticleNoteTitle`.
> Fix for #60 Unable to save non-parsable webpages

- src/parsers/MastodonParser.ts
- src/settings.ts
- src/views/settings-tab.ts
Added new settings to enable download of toot's media attachments. I also removed limitation to embed only images.
Settings are now reorganized and divided into sections where specific items are grouped based by content type.
> Add option to download Mastodon Media attachments

- README.md
- src/helpers/checkAndCreateFolder.ts
- src/main.ts
- src/parsers/StackExchangeParser.ts
- src/parsers/WebsiteParser.ts
- src/settings.ts
- src/views/settings-tab.ts
- tsconfig.json
New parser for Stack Exchange sites.
WebsiteParser cannot process whole Stack Exchange page. This new parser adds support for saving whole page and with own template and variables. 
Tested on multiple sites from Stack Exchange such as:
- https://askubuntu.com/questions/1452299/im-getting-the-error-the-following-security-updates-require-ubuntu-pro-with-e
- https://stackoverflow.com/questions/67230981/can-i-enable-exceptions-on-warnings-in-production
- https://stackoverflow.com/questions/69599286/how-do-you-make-text-flow-below-an-image
> feat: Add parser for Stack Exchange sites

- src/parsers/YoutubeParser.ts
Add comma to excluded characters list of YouTube API tags.
Ensure valid format of Obsidian tags.
https://www.youtube.com/watch?v=3zTCjT_5IFw
> fix: Add comma to excluded characters list of Youtube API tags

- src/views/settings-tab.ts
In the settings UI, the word "entered" appears twice as "enetred".  This PR replaces that typo with the correct spelling in both cases.
> Correct a typo in Settings UI

- src/parsers/BilibiliParser.ts
- src/parsers/TikTokParser.ts
- src/parsers/VimeoParser.ts
- src/parsers/YoutubeParser.ts
- src/settings.ts
- src/views/settings-tab.ts
This PR add new settings to customize size of embedded players in iframe element.
Feature request by user in issues.
By editing settings, checking saved data in data.json and creating notes with embedded player.
> feat: Add settings to customize embed player size

- src/parsers/BilibiliParser.ts
Bilibili embed player autoplays content by default. This behavior results in simultaneous playbacks in reading and editing mode. This fix adds ```autoplay=0``` query parameter to player URL which prevents autoplay.
#102 
Tested by creating new note from this Bilibili video: https://www.bilibili.com/video/BV1ru41147xd/
> fix: Bilibili embed autoplay

- src/parsers/YoutubeParser.ts
This PR provides fix for parsing HTML DOM of Youtube page. Youtube recently changed markup and broke getting video id from it.
Issue submitted by users.
Various Youtube videos such as:
- https://www.youtube.com/watch?v=GiTTihPxlqE
- https://www.youtube.com/watch?v=Jcoam1CeAq4
- https://www.youtube.com/watch?v=O0srjKOOR4g
> fix: Youtube video id from HTML DOM

- README.md
- src/parsers/WebsiteParser.ts
- src/views/settings-tab.ts
Add a `%previewURL%` variable containing the URL to the article preview image. The preview image is extracted from the DOM using the [OpenGraph](https://ogp.me/) `og:image` or the [Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) `twitter:image` meta tags. These two meta tags seem to be the most popular ones.
Small structure changes in the `WebsiteParser` file: avoiding wrapping promises, factorization of `replaceImages` and using `this.app` instead of passing it as a parameter.
I'm using this great plugin with the DataView plugin to display my items to read using a Card view. I really lacked an image to illustrate all my links. I was manually adding the preview image myself to the notes (sometimes using the dev tools to get the infos from the …
> feat: add preview image URL variable to articles

- src/parsers/TwitterParser.ts
This PR adds support for new Twitter domain - x.com. However, this domain is not supported by Twitter Publish API, so internally is overwritten to twitter.com.
Issue reported by user.
By saving public post - https://x.com/Windycom/status/1702327699564564602
> fix: Edit regex to support x.com in TwitterParser

- src/parsers/StackExchangeParser.ts
Fixes missing %date% template variables in StackExchange answer templates.
> Add missing %date% variables to answer template

- src/parsers/YoutubeParser.ts
Fix parsing of Schema.org data from HTML markup.
> fix: YouTube Schema.org parsing

- src/main.ts
- src/settings.ts
- src/views/settings-tab.ts
This PR adds new setting to open new notes in new tab instead of current workspace.
User request in https://github.com/DominikPieper/obsidian-ReadItLater/discussions/169
All possible settings combination.
> feat: Add setting to open new note in new tab

- src/parsers/BilibiliParser.ts
- src/parsers/MastodonParser.ts
- src/parsers/StackExchangeParser.ts
- src/parsers/TextSnippetParser.ts
- src/parsers/TikTokParser.ts
- src/parsers/TwitterParser.ts
- src/parsers/VimeoParser.ts
- src/parsers/WebsiteParser.ts
- src/parsers/YoutubeParser.ts
Use anonymous functions to return replacement strings where necessary to avoid issues caused by special replacement patterns in the content
The code heavily uses the pattern of replacing placeholders with specific content to achieve a template-like functionality. However, if the content contains special replacement patterns as mentioned in [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement), there will be issues with incorrect replacements. A minimal reproducible example:
```javascript
let template = ('[[ReadItLater]] [[Article]] %articleContent%')
let content = 'For …
```
> fix: Use anonymous functions to return replacement strings where necessary

- src/main.ts
- src/parsers/GithubParser.ts
- src/parsers/StackExchangeParser.ts
- src/parsers/WebsiteParser.ts
Although parsing of Github page was enhanced in #170 some repositories with shorter README were not parsed correctly. There was also empty link after heading. These issues was fixed in new Github parser.
Saving multiple repositories such as:
- https://github.com/obsidian-tasks-group/obsidian-tasks
- https://github.com/laravel/laravel
- https://github.com/okta/okta-sdk-dotnet
> feat: github parser

- README.md
- manifest.json
- package.json
- src/main.ts
- src/parsers/BilibiliParser.ts
- src/parsers/MastodonParser.ts
- src/parsers/Note.ts
- src/parsers/Parser.ts
- src/parsers/StackExchangeParser.ts
- src/parsers/TextSnippetParser.ts
- src/parsers/TikTokParser.ts
- src/parsers/TwitterParser.ts
- src/parsers/VimeoParser.ts
- src/parsers/WebsiteParser.ts
- src/parsers/YoutubeParser.ts
- src/settings.ts
- src/template/TemplateEngine.ts
- src/views/settings-tab.ts
Adds ability to use template variables in inbox and assets directory settings enabling more dynamic content creation.
User requested feature in #133 
> feat: inbox directories template variables

- src/parsers/WikipediaParser.ts
Fix WikipediaParser regex to support also m.wikipedia.org domain.
> fix: wikipedia parser regex support for m.wikipedia.org

- README.md
- src/ReadtItLaterApi.ts
- src/parsers/YoutubeParser.ts
- src/settings.ts
Add new template variable for YouTube content type with list of chapters with timestamped links.
User requested feature in #131 
> feat: add youtube chapters template variable

- src/parsers/YoutubeParser.ts
Fix accessing video tags.
User reported bug in #204 
Saving videos from #204 
> hotfix: youtube api

- src/parsers/WebsiteParser.ts
Provides fix for substack images. Specifically removes surrounding `<a>` tag that caused wrong markdown formatting.
Saving multiple Substack posts:
- https://www.pdole.ga/p/the-software-engineers-career-beyond
- https://www.pdole.ga/p/building-engineering-progression-7ca
> fix: substack images

- src/parsers/YoutubeParser.ts
Provides hotfix for Youtube parser not recognizing URL generated via share action in mobile app.
https://youtube.com/watch?v=r_e21HhG5Ko&si=6wzEDl9DfcNTP1ep
Bug reported by user in #217 
> hotfix: youtube parser regex

- src/helpers/fileutils.ts
- src/parsers/BlueskyParser.ts
Provides fix for striping out emojis from user defined filename templates.
Fix #219 
> hotfix: preserve emojis defined in filename template
